-- CREATE SCHEMA teg_olap;

CREATE TABLE teg_olap.Fact_CostEstimation(
    SKProjectCreatedAt INTEGER NOT NULL,
    SKVersionCreatedAt INTEGER NOT NULL,
    SKDimUser INTEGER NOT NULL,
    SKDimSubmesh INTEGER NOT NULL,
    SKDimMaterial INTEGER NOT NULL,
    AppliedUnitPrice_usd FLOAT(53) NOT NULL,
    SubmeshCost_usd FLOAT(53) NOT NULL,
    EstimatedWeight_g FLOAT(53) NOT NULL,
    PrintingTime_min FLOAT(53) NOT NULL
);
ALTER TABLE
    teg_olap.Fact_CostEstimation ADD PRIMARY KEY(SKProjectCreatedAt, SKVersionCreatedAt, SKDimUser, SKDimSubmesh, SKDimMaterial);


CREATE TABLE teg_olap.DimTime(
    SKDimTime INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullDate DATE NOT NULL,
    YearCode INTEGER NOT NULL,
    MonthCode INTEGER NOT NULL,
    DayOfYearCode INTEGER NOT NULL,
    DayOfMonthCode INTEGER NOT NULL,
    DayOfWeekCode INTEGER NOT NULL,
    WeekCode INTEGER NOT NULL,
    QuarterDesc INTEGER NOT NULL,
    SemesterDesc INTEGER NOT NULL,
    DayOfWeekDesc TEXT NOT NULL,
    DayOfWeekShortDesc TEXT NOT NULL,
    MonthDesc TEXT NOT NULL,
    MonthShortDesc TEXT NOT NULL
);


CREATE TABLE teg_olap.DimUser(
    SKDimUser INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID INTEGER NOT NULL,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    RegistrationDate DATE NOT NULL,
    isActive BOOLEAN NOT NULL
);


CREATE TABLE teg_olap.DimSubmeshVersion(
    SKDimSubmesh INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SubmeshID INTEGER NOT NULL,
    SubmeshName TEXT NOT NULL,
    Volume_cm3 FLOAT(53) NOT NULL,
    Area_cm2 FLOAT(53) NOT NULL,
    Bbox_x FLOAT(53) NOT NULL,
    Bbox_y FLOAT(53) NOT NULL,
    Bbox_z FLOAT(53) NOT NULL,
    ProjectID TEXT NOT NULL,
    VersionNumber FLOAT(53) NOT NULL,
    Gbbox_x FLOAT(53) NOT NULL,
    Gbbox_y FLOAT(53) NOT NULL,
    Gbbox_z FLOAT(53) NOT NULL,
    isDraft BOOLEAN NOT NULL,
    ProjectName TEXT NOT NULL,
    is3Dprinting BOOLEAN NOT NULL,
    isActive BOOLEAN NOT NULL
);


CREATE TABLE teg_olap.DimMaterial(
    SKDimMaterial INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaterialID INTEGER NOT NULL,
    MaterialName TEXT NOT NULL,
    Cost_usd FLOAT(53) NOT NULL,
    Weight_g FLOAT(53) NOT NULL,
    Measurement FLOAT(53) NOT NULL,
    Width FLOAT(53) NOT NULL,
    Length FLOAT(53) NOT NULL,
    Thickness FLOAT(53) NOT NULL,
    WastageFactor FLOAT(53) NOT NULL,
    MinPurchaseQuantity FLOAT(53) NOT NULL,
    MaterialClassID INTEGER NOT NULL,
    MaterialClassName TEXT NOT NULL,
    UnitID INTEGER NOT NULL,
    UnitAbbr TEXT NOT NULL,
    UnitName TEXT NOT NULL,
    DimensionID INTEGER NOT NULL,
    DimensionName TEXT NOT NULL,
    DensityUnitID INTEGER NOT NULL,
    DensityUnitAbbr TEXT NOT NULL,
    DensityValue FLOAT(53) NOT NULL,
    ThicknessUnitID INTEGER NOT NULL,
    ThicknessUnitAbbr TEXT NOT NULL
);


ALTER TABLE
    teg_olap.Fact_CostEstimation ADD CONSTRAINT fact_costestimation_skversioncreatedat_foreign FOREIGN KEY(SKVersionCreatedAt) REFERENCES teg_olap.DimTime(SKDimTime);
ALTER TABLE
    teg_olap.Fact_CostEstimation ADD CONSTRAINT fact_costestimation_skdimsubmesh_foreign FOREIGN KEY(SKDimSubmesh) REFERENCES teg_olap.DimSubmeshVersion(SKDimSubmesh);
ALTER TABLE
    teg_olap.Fact_CostEstimation ADD CONSTRAINT fact_costestimation_skdimmaterial_foreign FOREIGN KEY(SKDimMaterial) REFERENCES teg_olap.DimMaterial(SKDimMaterial);
ALTER TABLE
    teg_olap.Fact_CostEstimation ADD CONSTRAINT fact_costestimation_skdimuser_foreign FOREIGN KEY(SKDimUser) REFERENCES teg_olap.DimUser(SKDimUser);
ALTER TABLE
    teg_olap.Fact_CostEstimation ADD CONSTRAINT fact_costestimation_skprojectcreatedat_foreign FOREIGN KEY(SKProjectCreatedAt) REFERENCES teg_olap.DimTime(SKDimTime);