--CREATE SCHEMA teg_oltp;

CREATE TABLE teg_oltp.Users(
    UserID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT NOT NULL,
    Password TEXT NOT NULL,
    RegistrationDate DATE NOT NULL,
    isActive BOOLEAN NOT NULL
);


CREATE TABLE teg_oltp.Material(
    UserID INTEGER NOT NULL,
    MaterialID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaterialClassID INTEGER NOT NULL,
    Name TEXT NOT NULL,
    Cost_usd FLOAT(53) NOT NULL,
    UnitID INT NOT NULL,
    Weight_g FLOAT(53) NOT NULL,
    Measurement FLOAT(53) NULL,
    WastageFactor FLOAT(53) NOT NULL,
    MinPurchaseQuantity FLOAT(53) NOT NULL,
    DensityValue FLOAT(53) NULL,
    DensityUnitID INTEGER NULL,
    Length FLOAT(53) NULL,
    Width FLOAT(53) NULL,
    Thickness FLOAT(53) NULL,
    ThicknessUnitID INT NULL,
    isActive BOOLEAN NOT NULL
);


CREATE TABLE teg_oltp.MaterialClassification(
    MaterialClassID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name TEXT NOT NULL
);


CREATE TABLE teg_oltp.Dimension(
    DimensionID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name TEXT NOT NULL,
    CalculationMethod TEXT NOT NULL,
    Description TEXT NOT NULL
);


CREATE TABLE teg_oltp.Units(
    UnitID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DimensionID INTEGER NOT NULL,
    Name TEXT NOT NULL,
    Abbreviation TEXT NOT NULL,
    ConversionFactor FLOAT(53) NOT NULL,
    isBase BOOLEAN NOT NULL
);


CREATE TABLE teg_oltp.Submesh(
    ProjectID VARCHAR(26) NOT NULL,
    VersionNumber INTEGER NOT NULL,
    SubmeshID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SubmeshName TEXT NOT NULL,
    Volume_cm3 FLOAT(53) NOT NULL,
    Area_cm2 FLOAT(53) NOT NULL,
    Bbox_x FLOAT(53) NOT NULL,
    Bbox_y FLOAT(53) NOT NULL,
    Bbox_z FLOAT(53) NOT NULL
);


CREATE TABLE teg_oltp.Project(
    ProjectID VARCHAR(26) NOT NULL,
    UserID INTEGER NOT NULL,
    ProjectName TEXT NOT NULL,
    CreatedAt DATE NOT NULL,
    is3Dprinting BOOLEAN NOT NULL,
    isActive BOOLEAN NOT NULL
);


CREATE TABLE teg_oltp.MaterialAssignment(
    SubmeshID INTEGER NOT NULL,
    MaterialID INTEGER NOT NULL,
    AppliedUnitPrice_usd FLOAT(53) NOT NULL,
    SubmeshCost_usd FLOAT(53) NOT NULL,
    EstimatedWeight_g FLOAT(53) NOT NULL
);
ALTER TABLE
    teg_oltp.MaterialAssignment ADD PRIMARY KEY(SubmeshID, MaterialID);


CREATE TABLE teg_oltp.ProjectVersion(
    ProjectID VARCHAR(26) NOT NULL,
    VersionNumber INTEGER NOT NULL,
    Object3DURL TEXT NOT NULL,
    CostSnapshot_usd FLOAT(53) NOT NULL,
    CreatedAt DATE NOT NULL,
    EstimatedWeight_g FLOAT(53) NOT NULL,
    PrintingTime_min FLOAT(53) NOT NULL,
    Gbbox_x FLOAT(53) NOT NULL,
    Gbbox_y FLOAT(53) NOT NULL,
    Gbbox_z FLOAT(53) NOT NULL
);
ALTER TABLE
    teg_oltp.ProjectVersion ADD PRIMARY KEY(ProjectID, VersionNumber);


ALTER TABLE
    teg_oltp.MaterialAssignment ADD CONSTRAINT materialassignment_submeshid_foreign FOREIGN KEY(SubmeshID) REFERENCES teg_oltp.Submesh(SubmeshID);
ALTER TABLE
    teg_oltp.Material ADD CONSTRAINT material_materialclassid_foreign FOREIGN KEY(MaterialClassID) REFERENCES teg_oltp.MaterialClassification(MaterialClassID);
ALTER TABLE
    teg_oltp.Material ADD CONSTRAINT material_unitid_foreign FOREIGN KEY(UnitID) REFERENCES teg_oltp.Units(UnitID);
ALTER TABLE
    teg_oltp.Material ADD CONSTRAINT material_thicknessunitid_foreign FOREIGN KEY(ThicknessUnitID) REFERENCES teg_oltp.Units(UnitID);
ALTER TABLE
    teg_oltp.Units ADD CONSTRAINT units_dimensionid_foreign FOREIGN KEY(DimensionID) REFERENCES teg_oltp.Dimension(DimensionID);
ALTER TABLE
    teg_oltp.Submesh ADD CONSTRAINT submesh_projectversion_foreign FOREIGN KEY(ProjectID, VersionNumber) REFERENCES teg_oltp.ProjectVersion(ProjectID, VersionNumber);
ALTER TABLE
    teg_oltp.Material ADD CONSTRAINT material_userid_foreign FOREIGN KEY(UserID) REFERENCES teg_oltp.Users(UserID);
ALTER TABLE
    teg_oltp.Project ADD CONSTRAINT project_userid_foreign FOREIGN KEY(UserID) REFERENCES teg_oltp.Users(UserID);
ALTER TABLE
    teg_oltp.ProjectVersion ADD CONSTRAINT projectversion_projectid_foreign FOREIGN KEY(ProjectID) REFERENCES teg_oltp.Project(ProjectID);
ALTER TABLE
    teg_oltp.Material ADD CONSTRAINT material_densityunitid_foreign FOREIGN KEY(DensityUnitID) REFERENCES teg_oltp.Units(UnitID);
ALTER TABLE
    teg_oltp.MaterialAssignment ADD CONSTRAINT materialassignment_materialid_foreign FOREIGN KEY(MaterialID) REFERENCES teg_oltp.Material(MaterialID);